[project]
name = "hexagonal-jps-pygame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "typing>=3.10.0.0",
]
